### PR TITLE
Adds new dimensions campaign group and placement

### LINKED ISSUE #25: Additional modern campaign tracking parameters
I'm in the process of transitioning from Google Analytics to Matomo. Tracking advertising campaigns is not as powerful in Matomo because the campaign tracking parameters (pk_*) are limited to equivalents of the old utm parameters that Urchin defined decades ago. These parameters are useful but they don't cover all the dimensions needed to track an advertising campaign today.

The big ad platforms no longer rely on utm parameters for their analytics. Instead, they have their own proprietary "click id" parameters (gclid, fbclid, mscklid) [that allow a lot more useful information to be tracked in a single query string parameter](https://support.google.com/analytics/answer/1733663?hl=en). This puts Matomo at a big disadvantage because it doesn't have important dimensions such as target audience and ad placement/positioning. These details are available via URL templates so the only thing preventing Matomo from getting them is Matomo's own limitation.

Currently I'm passing them through by combining multiple fields from the ad platforms into Matomo pk parameters. For example, I'm putting both the Ad Group and the search keywords in pk_keywords and I'm putting the Ad ID and the Ad placement in pk_content. This doesn't work very well because they're independent dimensions but are being forced together so analysis and reporting on them is less powerful.

I propose that Matomo add additional pk_ parameters to track important dimensions that a marketer today can't really be effective without. For example, you might add

- pk_group or pk_audience for the target audience
- pk_placement or pk_position for where the ad showed up to the visitor
- pk_etc for additional (maybe platform specific) data that is useful but isn't common enough across platforms to justify a standard parameter

In my opinion, if Matomo wants to complete in today's market it needs to innovate and not just follow a defactor standard from 20 years ago. As the leading open 3rd party analytics platform you have the opportunity to set the new standard.

An alternative solution might be making it easy for users to define their own campaign parameters but I'd prefer to see Matomo define the more common ones as standard.

### PR DESCRIPTION
**Pull request by sgiehl**
This PR adds two new visit dimensions: Campaign Group and Campaign Placement
They are detected using configurable url parameters (defaults: mtm_group/pk_group and mtm_placement/pk_placement)
Their values will appear together with the other campaign parameters in visits log
For both dimensions there will be new reports in the campaigns section

To clarify:
* Would it maybe make sense to have one of the new dimensions as subtable report for another (like it's currently for campaign name -> campaign keyword)

fixes #25

### CODE REVIEW

**Comment by tsteur** [comment]
> Would it maybe make sense to have one of the new dimensions as subtable report for another (like it's currently for campaign name -> campaign keyword)

I suppose we could always add it later if needed? I guess it's hard to say as everyone would maybe want a different subtable and easiest be for now to maybe use custom reports to get what they are after

**Comment by sgiehl** [comment]
Sure, we can add that later at any time.

**Comment by tsteur** [comment]
btw in core we will also need to adjust the campaign generator

**Comment by diosmosis** [comment]
@sgiehl I guess we should create an issue for modifying the campaign generator?

**Comment by sgiehl** [comment]
sure. makes sense

**Pull request merged**
